- include: config.yml

- name: Create qdrouterd configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    host: "{{coe_host}}"
    context: "{{kube_context}}"
    kubeconfig: "{{config_file}}"
    name: qrouterd
    namespace: openstack
    state: present
    debug: yes
    labels:
      service: qdrouterd
    data:
      kolla-config: |
        {
        "command": "/usr/sbin/qdrouterd",
        "config_files": [],
        "permissions": [
          {
            "path": "/var/lib/qdrouterd",
            "owner": "qdrouterd:qdrouterd",
            "recurse": true
          },
          {
            "path": "/var/log/kolla/qdrouterd",
            "owner": "qdrouterd:qdrouterd",
            "recurse": true
          }
          ]
        }
      qdrouterd-sasl.conf: |
        {{ qdrouterd_sasl_confs['content'] | b64decode }}
      qdrouterd.conf: |
        {{ qdrouterd_confs['content'] | b64decode  }}

- name: Create qdrouterd service
  k8s_v1_service:
    host: "{{coe_host}}"
    context: "{{kube_context}}"
    kubeconfig: "{{config_file}}"
    name: qdrouterd
    namespace: openstack
    state: present
    ports:
      - port: '{{qdrouterd_port}}'
        name: qdrouterd
    selector:
      app: qdrouterd
    labels:
      app: qdrouterd
    debug: yes
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  register: create_service

- name: Create qdrouterd deployment
  k8s_v1beta1_deployment:
    host: "{{coe_host}}"
    context: "{{kube_context}}"
    kubeconfig: "{{config_file}}"
    name: qdrouterd
    namespace: openstack
    state: present
    debug: yes
    spec_template_metadata_name: qdrouterd
    spec_template_metadata_labels:
      app: qdrouterd
      galera: enabled
    containers:
      - name: qdrouterd
        image: tripleoupstream/centos-binary-qdrouterd
        ports:
        - container_port: '{{qdrouterd_port}}'
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
        volume_mounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
        - name: qdrouterd-conf
          mountPath: /etc/qdrouterd/qdrouterd.conf
        - name: qdrouterd-sasl-conf
          mountPath: /etc/sasl/qdrouterd-sasl.conf
    replicas: 1
    volumes:
      - name: kolla-config
        config_map:
          name: qdrouterd
          items:
            - key: kolla-config
              path: config.json
      - name: qdrouterd-conf
        config_map:
          name: qdrouterd
          items:
            - key: qdrouterd.conf
              path: qdrouterd.conf
      - name: qdrouterd-sasl-conf
        config_map:
          name: qdrouterd
          items:
            - key: qdrouterd-sasl.conf
              path: qdrouterd-sasl.conf
